'''Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum 
and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
Link: https://projecteuler.net/problem=44'''

#Imports
import time

#Build a pentagonals function
def P(n):
    return (n * ((3 * n) - 1)) / 2
    
#Build an isPentagonal function
#Note: this was derived by using the quadratic
#formula on the initial equation, (N(3N - 1)) / 2
#where the formula is ax^2 + bx + c. When we simplify
#our equation into this form, we get 3/2N^2 -N/2 - n = 0
#and from this we get: a = 3/2, b = -1/2, and c = -n
#Using these values in the quadratic equation, we get
#X = (0.5 + (0.25 + 6 * n)**0.5) / 3
def isP(n):
    ans = (0.5 + (0.25 + (6 * n))**0.5) / 3
    return ans == int(ans)

#Build a solve function
def solve():
    #Define variables
    s                 = time.time()
    k, notfound       = 2, True
  
    #For every pentagonal, check every
    #pentagonal below it for the given condition.
    #Since we're looking for the smallest difference,
    #we start at P(k) = P(j - 1) and work our way down.
    #Note: since pentagonal numbers grow O(n^2), as they
    #get larger, the differences between any two grow as
    #well, therefore, the first set we find that fulfill
    #the requirements is necessarily the smallest
    #possible difference, and thus, our answer.
    while notfound:
        pk = P(k)        
        for j in range(k - 1, 0, -1):
            pj= P(j)
            if isP(pj + pk):
                d  = abs(Pk - Pj)
                if isP(d):
                    notfound = False
                    break
        k += 1
        
    d, pj, pk, j, k = str(d), str(pj), str(pk), str(j), str(k)
    
    #Print the results
    print 'When j = ' + j + ' and k = ' + k + '; P(j) = ' + pj + ', '
    print 'P(k) = ' + pk + ', the sum and difference of P(k) '
    print 'and P(j) are pentagonal, and D, which both equals '
    print '|P(k) - P(j)|, and is minimized, equals ' + d + '.'
    print 'This took ' + str(time.time() - s) + ' seconds to calculate.'

#Run the program
solve()
